#include<iostream>
using namespace std;
int main() {
    /*
    int x,y;
     cout <<"enter the value y "<< endl;
   cin >> y ;
    cout <<"enter the value x "<< endl;
    cin>> x ;
    cout << "Numbers x and y are --"<< x <<"\t"<< y << "\n " ;
    if(x>y)
    {
        cout<<"x is greater than y"<< endl;
    }
    else if(x<=y)
    {
        cout<<"y is greater than x"<< endl;
    }
    // new programm
   int a,b;
   cout<< "Enter the value of A "<< endl;
   cin>>a;
  // cout<< "Enter the value of B "<< endl;
  // cin>>b;
   if(a>0){
    cout<<"a is positive ";
   }
   else if(a<0){
    cout<<"A is negative ";
   }
   else{
    cout<< "The Enter Number is zero";

    
   }
   */
}